steps:
  # Build and push gRPC server image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'
      - '.'

  # Build and push Envoy sidecar image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.envoy'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}-envoy:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}-envoy:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}-envoy'

  # Deploy to Cloud Run using service.yaml
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -e "s|\$${PROJECT_ID}|${PROJECT_ID}|g" \
            -e "s|\$${REGION}|${_REGION}|g" \
            -e "s|\$${REPO_NAME}|${_REPO_NAME}|g" \
            -e "s|\$${CLOUDSQL_INSTANCE}|${_CLOUDSQL_INSTANCE}|g" \
            -e "s|\$${DB_NAME}|${_DB_NAME}|g" \
            -e "s|\$${DB_USER}|${_DB_USER}|g" \
            -e "s|\$${SERVICE_ACCOUNT}|${_SERVICE_ACCOUNT}|g" \
            -e "s|\$${TAG}|${_TAG}|g" \
            -e "s|\$${FRONTEND_URL}|${_FRONTEND_URL}|g" \
            service.yaml > service-resolved.yaml
        gcloud run services replace service-resolved.yaml --region=${_REGION}
        gcloud run services set-iam-policy ${_SERVICE_NAME} --region=${_REGION} policy.yaml 2>/dev/null || \
          gcloud run services add-iam-policy-binding ${_SERVICE_NAME} --region=${_REGION} --member=allUsers --role=roles/run.invoker

substitutions:
  _REGION: asia-northeast1
  _REPO_NAME: postgres-prod
  _SERVICE_NAME: postgres-prod
  _CLOUDSQL_INSTANCE: ''  # Set via trigger
  _DB_NAME: myapp
  _DB_USER: ''  # Set via trigger (IAM user email)
  _SERVICE_ACCOUNT: ''  # Set via trigger
  _TAG: latest  # Default tag, can be overridden
  _FRONTEND_URL: 'https://mtama-front.mtamaramu.com/auth/callback'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}-envoy'
