apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: postgres-prod
  annotations:
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: cloudsql-sv:asia-northeast1:postgres-prod
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: '{"grpc-server":["envoy"]}'
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      serviceAccountName: 747065218280-compute@developer.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        # Envoy sidecar - ingress container (receives traffic on port 8080)
        - name: envoy
          image: asia-northeast1-docker.pkg.dev/cloudsql-sv/postgres-prod/postgres-prod-envoy@sha256:0c39d2a3829364f8ba051a185745b696badca6bbc86820ff4392c05166f8b0c9
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 10

        # gRPC server - main application (internal, port 9090)
        - name: grpc-server
          image: asia-northeast1-docker.pkg.dev/cloudsql-sv/postgres-prod/postgres-prod@sha256:0b1aaf2399800f9fab69b39f9f8db61a1ceaba0d2f37b9776b781243120cca44
          env:
            - name: PORT
              value: "9090"
            - name: GCP_PROJECT_ID
              value: cloudsql-sv
            - name: GCP_REGION
              value: asia-northeast1
            - name: CLOUDSQL_INSTANCE_NAME
              value: postgres-prod
            - name: DB_NAME
              value: myapp
            - name: DB_USER
              value: 747065218280-compute@developer
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: JWT_SECRET
                  key: latest
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_CLIENT_ID
                  key: latest
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_CLIENT_SECRET
                  key: latest
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_REDIRECT_URI
                  key: latest
            - name: FRONTEND_URL
              value: "https://mtama-front.mtamaramu.com/auth/callback"
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
